# Generated by Django 3.0.7 on 2020-06-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=200, unique=True)),
                ('merchant_email', models.CharField(max_length=200)),
                ('merchant_username', models.CharField(max_length=200)),
                ('merchant_password', models.CharField(max_length=200)),
            ],
        ),
    ]
