# Generated by Django 3.0.7 on 2020-06-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=50)),
                ('storage', models.PositiveIntegerField()),
                ('camera', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.PositiveIntegerField()),
            ],
        ),
    ]
